
project_id = "yfnqnsgggcbkdqhdlocd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "https://lovable.dev"
additional_redirect_urls = ["http://localhost:3000", "https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_anonymous_users = false

[auth.external.google]
enabled = false

[auth.external.github]
enabled = false

[db]
port = 54322

[functions.process-tender]
verify_jwt = true

[functions.export-tender]  
verify_jwt = true

[functions.regenerate-response]
verify_jwt = true

[functions.rewrite-response]
verify_jwt = true

[functions.upsert-memory]
verify_jwt = true

[functions.demo-response]
verify_jwt = false

[edge-runtime]
inspector_port = 8083

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[studio]
enabled = true
port = 54324
